# Generated by Django 4.1.7 on 2023-05-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMinuteMeans',
            fields=[
                ('symbol', models.OneToOneField(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='real_time.companies')),
                ('weekday', models.CharField(max_length=12)),
                ('timestamp', models.TimeField()),
                ('change', models.FloatField(blank=True, null=True)),
                ('change_std', models.FloatField(blank=True, null=True)),
                ('standardized_mean', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_minute_means',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MinuteMeans',
            fields=[
                ('symbol', models.OneToOneField(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='real_time.companies')),
                ('timestamp', models.TimeField()),
                ('change', models.FloatField(blank=True, null=True)),
                ('change_std', models.FloatField(blank=True, null=True)),
                ('standardized_mean', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'minute_means',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='intradayprices',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': False},
        ),
    ]
